# Generated by Django 4.1.1 on 2022-09-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(1, 'Perro'), (2, 'Gato'), (3, 'Loro'), (4, 'Llama'), (5, 'Capibara')], default=1)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='webapi.persona')),
            ],
        ),
    ]
