# Generated by Django 4.1.1 on 2024-02-16 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_tipocondominio_tipodivision_condominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pisos', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('condominioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominioId_bloque', to='webapi.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='DivisionManzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_lotes', models.IntegerField()),
                ('condominioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominioId_manzana', to='webapi.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('manzanaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manzanaId', to='webapi.divisionmanzana')),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('bloqueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueId_piso', to='webapi.divisionbloque')),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='rest_plat',
            name='plato',
        ),
        migrations.RemoveField(
            model_name='rest_plat',
            name='restaurante',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Plato',
        ),
        migrations.DeleteModel(
            name='Rest_Plat',
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='pisoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pisoId', to='webapi.piso'),
        ),
    ]
