# Generated by Django 4.1.1 on 2024-02-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_divisionbloque_divisionmanzana_inmueble_piso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='superficie',
            field=models.IntegerField(default=False),
        ),
    ]
