# Generated by Django 4.1.1 on 2024-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0005_condominio_activo_inmueble_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='creador',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
